---
title: "TractorRegionDiffusion"
author: "Kyle Amyx"
date: "6/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(tidyverse)
```


```{r data, echo = FALSE}
rolledUp_all <- read_csv("Tractor_Raw_Data/rolledUp_all.csv")
rolledUp_all$X1 <- NULL
```



```{r regionDiff, echo=FALSE}
library(ggplot2)

# South-Central(AL, MS, TN) within region plot
southCentral <- subset(rolledUp_all, stateAbb %in% c("AL", "MS", "TN"))
ggplot(southCentral, aes(x = year, y = percent)) +
  geom_line(aes(group = stateAbb, colour = stateAbb)) +
  labs(title = " South-Central within region diffusion", x = "Year", y = "% Farms w/ Tractors")

rolledUp_southCentral <- southCentral %>% 
  group_by(year) %>%
  summarise(percent = sum(percent)/3, region = "SC")

# South-West(AR,OK,LA,TX) within region plot
southWest <- subset(rolledUp_all, stateAbb %in% c("AR", "OK", "LA", "TX"))
ggplot(southWest, aes(x = year, y = percent)) +
  geom_line(aes(group = stateAbb, colour = stateAbb)) +
  labs(title = " South-West within region diffusion", x = "Year", y = "% Farms w/ Tractors")

rolledUp_southWest <- southWest %>% 
  group_by(year) %>%
  summarise(percent = sum(percent)/3, region = "SW")


# South-East(NC,SC,GA,FL) within region plot
southEast <- subset(rolledUp_all, stateAbb %in% c("NC", "SC", "GA", "FL"))
ggplot(southEast, aes(x = year, y = percent)) +
  geom_line(aes(group = stateAbb, colour = stateAbb)) +
  labs(title = "South-East within region diffusion", x = "Year", y = "% Farms w/ Tractors")

rolledUp_southEast <- southEast %>% 
  group_by(year) %>%
  summarise(percent = sum(percent)/3, region = "SE")





```

# Visualize diffusion by the 3 regions
```{r regionRolledUpDiff, echo =FALSE}
regions <- rbind(rolledUp_southCentral, rolledUp_southEast, rolledUp_southWest)

ggplot(regions, aes(x = year, y = percent)) +
  geom_line(aes(group = region, colour = region)) +
  labs(title = " Between Region diffusion", x = "Year", y = "% Farms w/ Tractors")

```